### ISSUE TITLE
Update from 1.3.0 to 1.4.2 breaks application, when YII_ENV=test

### ISSUE THREAD

**Issue by schmunk42** [codemix/yii2-localeurls#62]
When I update from 1.3.0 to 1.4.2, I get an exception for most requested pages (see below), but just during testing (`dev` and `prod` works) - any idea what may cause this?

I have this setting enabled:

```
'enableDefaultLanguageUrlCode' => true,
```

And I also set:

```
'showScriptName' => false,
```

```
[28-Feb-2016 22:41:20] WARNING: [pool www] child 18 said into stderr: "2016-02-28 22:41:20 [192.168.172.1][-][-][error][yii\base\Exception] exception 'yii\base\Exception' with message '/de' in /app/vendor/codemix/yii2-localeurls/UrlManager.php:425"
[28-Feb-2016 22:41:20] WARNING: [pool www] child 18 said into stderr: "Stack trace:"
[28-Feb-2016 22:41:20] WARNING: [pool www] child 18 said into stderr: "#0 /app/vendor/codemix/yii2-localeurls/UrlManager.php(348): codemix\localeurls\UrlManager->redirectToLanguage('de')"
[28-Feb-2016 22:41:20] WARNING: [pool www] child 18 said into stderr: "#1 /app/vendor/codemix/yii2-localeurls/UrlManager.php(171): codemix\localeurls\UrlManager->processLocaleUrl(Object(yii\web\Request))"
[28-Feb-2016 22:41:20] WARNING: [pool www] child 18 said into stderr: "#2 /app/vendor/yiisoft/yii2/web/Request.php(180): codemix\localeurls\UrlManager->parseRequest(Object(yii\web\Request))"
[28-Feb-2016 22:41:20] WARNING: [pool www] child 18 said into stderr: "#3 /app/vendor/yiisoft/yii2/web/Application.php(75): yii\web\Request->resolve()"
[28-Feb-2016 22:41:20] WARNING: [pool www] child 18 said into stderr: "#4 /app/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))"
[28-Feb-2016 22:41:20] WARNING: [pool www] child 18 said into stderr: "#5 /app/web/index.php(15): yii\base\Application->run()"
[28-Feb-2016 22:41:20] WARNING: [pool www] child 18 said into stderr: "#6 {main}"
172.17.0.6 -  28/Feb/2016:22:41:21 +0000 "GET /index.php" 200
172.17.0.6 -  28/Feb/2016:22:41:24 +0000 "GET /index.php" 500
[28-Feb-2016 22:41:24] WARNING: [pool www] child 17 said into stderr: "2016-02-28 22:41:24 [192.168.172.1][-][-][error][yii\base\Exception] exception 'yii\base\Exception' with message '/en' in /app/vendor/codemix/yii2-localeurls/UrlManager.php:425"
[28-Feb-2016 22:41:24] WARNING: [pool www] child 17 said into stderr: "Stack trace:"
[28-Feb-2016 22:41:24] WARNING: [pool www] child 17 said into stderr: "#0 /app/vendor/codemix/yii2-localeurls/UrlManager.php(348): codemix\localeurls\UrlManager->redirectToLanguage('en')"
[28-Feb-2016 22:41:24] WARNING: [pool www] child 17 said into stderr: "#1 /app/vendor/codemix/yii2-localeurls/UrlManager.php(171): codemix\localeurls\UrlManager->processLocaleUrl(Object(yii\web\Request))"
[28-Feb-2016 22:41:24] WARNING: [pool www] child 17 said into stderr: "#2 /app/vendor/yiisoft/yii2/web/Request.php(180): codemix\localeurls\UrlManager->parseRequest(Object(yii\web\Request))"
[28-Feb-2016 22:41:24] WARNING: [pool www] child 17 said into stderr: "#3 /app/vendor/yiisoft/yii2/web/Application.php(75): yii\web\Request->resolve()"
[28-Feb-2016 22:41:24] WARNING: [pool www] child 17 said into stderr: "#4 /app/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))"
[28-Feb-2016 22:41:24] WARNING: [pool www] child 17 said into stderr: "#5 /app/web/index.php(15): yii\base\Application->run()"
[28-Feb-2016 22:41:24] WARNING: [pool www] child 17 said into stderr: "#6 {main}"
172.17.0.6 -  28/Feb/2016:22:41:25 +0000 "GET /index.php" 500
```

**Comment by mikehaertl** [comment]
Yes, it's because of this here:
https://github.com/codemix/yii2-localeurls/blob/master/UrlManager.php#L425

It was the only way to test the redirects in the test cases. Hmm. Not sure yet, how to fix this.

**Comment by mikehaertl** [comment]
@schmunk42 Actually I think, you should fix your test cases, so that they don't trigger any redirect from this extension. Your test cases would probably not work correctly anyway if there's a redirect.

**Comment by schmunk42** [comment]
Hmmm, we explicitly test redirects in our acceptance test cases, since this is one of the parts we often have problems with (eg. wrong SEO indexing, empty pages for en_us while en is fine, etc...).

**Comment by mikehaertl** [comment]
@schmunk42 We already have very extensive tests in the extension itself. We test for all kinds of different scenarios so I don't think you need to test for this again in your app. If you find, that a test is missing I'm happy to include it here.

So can we close this?

**Comment by schmunk42** [comment]
Yes, closed. Thank you.

**Comment by schmunk42** [comment]
Can we get something like

```
if (getenv('LOCALEURLS_TEST')) {
```

instead of using `YII_ENV_TEST`? Just pass this by setting a variable or constant in the test config.

Since this component is so deeply integrated into the application lifecycle, it's impossible to work around this issue in acceptance tests.

I'd be ready for a PR about this.

🙇

**Comment by mikehaertl** [comment]
Ok, should not hurt. I've committed a change. Does this solve it for you?

**Comment by schmunk42** [comment]
Perfect, thank you! A release would be the last thing ;)

**Comment by mikehaertl** [comment]
Done!

**Comment by schmunk42** [comment]
Ooops, undefined variable, see PR.

**Comment by mikehaertl** [comment]
Ouch, ok. But no PR so far...?
